# For testing

version: "3.4"

services:
  test_db:
    image: postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  test_api:
    build:
      dockerfile: ./api/Dockerfile
      context: ./
      target: dev
    volumes:
      - ./api/src:/usr/agori/api/src
      - ./api/tests:/usr/agori/api/tests
    env_file:
      - ./api/.env.example
      - ./api/.env.test
    depends_on:
      - test_db

volumes:
  postgres_data:
