name: Test API

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build container
        run: docker-compose -f docker-compose.test.yml build
      - name: Run tests
        run: docker-compose -f docker-compose.test.yml run test_api test --ci
